CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" (
    "total_nb_trx_1h" BIGINT,
    "total_fee_1h"    BIGINT,
    "avg_fee_1h"      REAL
);
CREATE OR REPLACE PUMP "STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
    SELECT STREAM  
        COUNT("tx_hash"), 
        SUM("tx_fee"), 
        AVG("tx_fee")
        FROM "SOURCE_SQL_STREAM_001"
        GROUP BY STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '1' HOUR);
